package dev.stan.workutils.dymax.iconic;

import java.util.HashMap;


public class IconicList {

	private static HashMap<String,String> list = new HashMap<String,String>();

	public static HashMap<String,String> generateList(){
		list.put("E7X","*Fort Worth - Eastchase");
		list.put("EGM","*Kent - Marketplace at Lake Meridian");
		list.put("EGB","*Scottsdale - Ancala Village");
		list.put("EGE","*St. George - Pioneer Road");
		list.put("E9G","*Toms River - Tri City Plaza");
		list.put("E9J","Aberdeen - Aberdeen Town Square");
		list.put("EAS","Acton - Acton Plaza");
		list.put("E04","Agoura Hills - Oak Creek");
		list.put("E25","Alamogordo - White Sands");
		list.put("A65","Albany - Clay St");
		list.put("EBL","Albany - Westgate SC");
		list.put("C39","Albuquerque - Eubank Plaza");
		list.put("D37","Albuquerque - Montano");
		list.put("B75","Albuquerque - Quail Plaza");
		list.put("E6F","Albuquerque - San Pedro");
		list.put("A20","Albuquerque - Sycamore Plaza");
		list.put("E83","Alpharetta - Windward Parkway");
		list.put("D19","Alpine - Alpine Village");
		list.put("EA1","Amherst - Ambriar SC");
		list.put("ECU","Amherst - Deerfield TC");
		list.put("ECF","Amsterdam - Amsterdam Commons");
		list.put("E21","Anaheim Hills - Festival");
		list.put("EBW","Anaheim Hills - Santa Ana Canyon Center");
		list.put("EF2","Anthem - Anthem Crossroads");
		list.put("ECB","Arlington Heights - Arlington Towne Square");
		list.put("EH7","Ashland - Claremont Avenue");
		list.put("EH8","Athens - University Mall");
		list.put("E84","Atlanta - Buford Hwy");
		list.put("A99","Auburn - Supermall Way");
		list.put("E26","Aurora - Salida Shops");
		list.put("B68","Aurora - Tower Crossing");
		list.put("EHI","Avon - French Creek Square");
		list.put("E6L","Bainbridge Island - Island Village");
		list.put("D96","Baker City - Baker Towne Square");
		list.put("D53","Bakersfield - Mt. Vernon II");
		list.put("A70","Bakersfield - Riverlakes");
		list.put("C76","Bakersfield - Rosedale Gateway");
		list.put("A79","Bakersfield - Town & Country");
		list.put("C30","Battle Ground - Battle Ground Square");
		list.put("E9O","Bayonne - South Cove Commons");
		list.put("B86","Beaverton - Griffith Park");
		list.put("ECG","Bedford - Bedford Grove");
		list.put("E7R","Bee Cave - Hill Country Galleria");
		list.put("ECW","Bellefontaine - Fontaine Plaza");
		list.put("B85","Bellingham - Bakerview");
		list.put("ECH","Belmont - Belknap Mall");
		list.put("EBB","Bend - Borden's Corner");
		list.put("EBC","Bennington - Main Street");
		list.put("ECX","Bexley - E. Main Street");
		list.put("EDJ","Blackfoot - Parkway Village");
		list.put("B48","Blythe - Hobson Way");
		list.put("EDK","Boise - Boise Town Square II");
		list.put("EEJ","Boise - Broadway Avenue");
		list.put("EEE","Boise - Marketplace SC");
		list.put("EF3","Boise - W. Emerald Street");
		list.put("EEW","Boise - W. Overland Road");
		list.put("EER","Boise - Water's Edge");
		list.put("ECT","Bonita Springs - Center of Bonita Springs");
		list.put("E65","Bonney Lake - Bonney Lake Plaza");
		list.put("D10","Bonney Lake - Bonney Lake Town Center");
		list.put("EF4","Boulder City - Village Square");
		list.put("EDL","Bountiful - Gateway Crossing SC");
		list.put("EDM","Bozeman - Gallatin Valley Mall II");
		list.put("EEI","Bozeman - S. 11th Avenue");
		list.put("EGW","Bradenton - Lakewood Ranch");
		list.put("EGT","Bradenton - Promenade");
		list.put("E80","Brandon - Premier Plaza");
		list.put("E9A","Brandywine - Brandywine Crossing");
		list.put("EHA","Brecksville - Creekview Commons");
		list.put("D99","Bremerton - Bremerton Plaza");
		list.put("E6M","Bremerton - Oyster Bay Plaza");
		list.put("E9Q","Bridgehampton - Bridgehampton Commons");
		list.put("E8K","Bridgeton - Bridgeton Retail Center");
		list.put("EDN","Brigham City - Skyline Retail Center");
		list.put("EI2","Brooklyn - Ridge Park Square");
		list.put("EI3","Brooklyn - Ridge Park Square II");
		list.put("C26","Broomfield - Quail Creek");
		list.put("C68","Buckeye - Sundance Towne Center");
		list.put("E6U","Bullhead City - City Square");
		list.put("EFY","Bullhead City - Mohave Crossroads");
		list.put("EEK","Burley - N. Overland Avenue");
		list.put("EEB","Burley - Overland Avenue");
		list.put("D22","Burlington - Cross Court Plaza");
		list.put("EEL","Caldwell - Cleveland Blvd.");
		list.put("EC4","Campbell - E. Hamilton Ave.");
		list.put("EHB","Canal Winchester - Waterloo Crossing");
		list.put("C84","Canby - Canby Place");
		list.put("E37","Canon City - Fremont Drive");
		list.put("EC5","Capitola - 41st Street");
		list.put("EB2","Carlsbad - La Costa TC");
		list.put("ECZ","Carrollton - Sherwood Village");
		list.put("B37","Castle Rock - Founders Parkway");
		list.put("E7F","Castle Rock - The Shops on Meadows");
		list.put("EF5","Cave Creek - Carefree Hwy.");
		list.put("EF7","Cedar City - Renaissance Square");
		list.put("EF6","Cedar City - S. Providence Center");
		list.put("A00","Cell Adjustments");
		list.put("EEM","Centerville - Centerville Marketplace");
		list.put("EH9","Chagrin Falls - McFarland's Corner");
		list.put("EHC","Chagrin Falls - Tanglewood Square");
		list.put("E9H","Chambersburg - Chambersburg Crossing");
		list.put("A23","Chandler - Boulevard Shops");
		list.put("EG5","Chandler - Riggs Marketplace");
		list.put("EH6","Charlotte - Packard Hwy");
		list.put("D18","Chehalis - Twin City Town Ctr");
		list.put("E9B","Chesapeake - Cahoon Commons");
		list.put("E95","Chesapeake - Chesapeake Square");
		list.put("E8Y","Chesapeake - Crossways");
		list.put("E92","Chester - Red Apple Market");
		list.put("E8S","Chesterfield - THF Boulevard");
		list.put("E42","Cheyenne - Frontier Mall");
		list.put("ED0","Chillicothe - Zane Plaza");
		list.put("E94","Cinnaminson - The Shoppes at Cinnaminson");
		list.put("EHD","Circleville - Circleville Plaza");
		list.put("ED1","Circleville - US HWY 23");
		list.put("EEN","Clinton - W 1800 N");
		list.put("C47","Clovis - Clovis Commons");
		list.put("E9E","Cockeysville - York Village");
		list.put("E51","Colorado Springs - University Village");
		list.put("EDO","Columbia Falls - 9th Street W");
		list.put("EHG","Columbus - Blacklick Creek SC");
		list.put("EHK","Columbus - Georgesville");
		list.put("EHE","Columbus - N. High Street");
		list.put("EHZ","Columbus - Polaris Neighborhood Center II");
		list.put("EI4","Columbus - S. High Street");
		list.put("EFN","Coolidge - N. Arizona Blvd.");
		list.put("D60","Cornelius - Cornelius Gateway");
		list.put("B65","Corvallis - Timberhills");
		list.put("B88","Cypress - Katella");
		list.put("D07","Dallas - Mill Valley Square");
		list.put("E8D","Davenport - Hwy 27");
		list.put("E86","Dawsonville - Promenade");
		list.put("C19","Del Mar - Highlands");
		list.put("EHF","Delaware - Georgetowne Centre");
		list.put("E38","Delta - Main Street");
		list.put("B04","Denver - Hampden");
		list.put("ECI","Derry - Manchester Road");
		list.put("EDQ","Dillon - N. Montana Street");
		list.put("D78","Draper - Draper Crossing");
		list.put("EDP","Driggs - S. Main Street");
		list.put("EI5","Dublin - Sawmill");
		list.put("E39","Durango - S. Camino del Rio");
		list.put("EEO","Eagle - Eagle Promenade");
		list.put("E9T","East Brunswick - Brunswick Square Mall");
		list.put("A95","eCommerce");
		list.put("EA8","Edgartown - Vineyard Haven Road");
		list.put("EAK","Edison - Edison Commons SC");
		list.put("C55","El Paso - El Paseo Marketplace");
		list.put("D48","El Paso - North Mesa");
		list.put("C42","El Paso - Zaragoza");
		list.put("ECC","Elgin - Otter Creek SC");
		list.put("EAZ","Elko - Argent Avenue");
		list.put("E9K","Elverson - Morgantown Crossing");
		list.put("EEP","Emmett - Shops at Emmett");
		list.put("E6R","Enumclaw - Market Square");
		list.put("A90","Escondido - Valley Parkway");
		list.put("EBD","Essex Junction - Park Street");
		list.put("EB6","Eugene - Acorn Park");
		list.put("D38","Evergreen - Evergreen Center");
		list.put("EBS","Fairbanks - Airport Way");
		list.put("C62","Fallbrook - Towne Center");
		list.put("E60","Farmington - East Main");
		list.put("EHH","Findlay - Interstate");
		list.put("E14","Firestone - Kings Center");
		list.put("E9C","Forest - Graves Mill Center");
		list.put("E40","Fort Collins - Front Range Village");
		list.put("EFZ","Fort Mohave - Hwy 95");
		list.put("ECS","Fort Myers - Gulf Coast TC 2");
		list.put("E87","Fort Myers - Market Square Plaza");
		list.put("E8B","Fort Myers - The Shoppes at Island Pass");
		list.put("E7T","Fort Worth - Alliance Town Center");
		list.put("EF8","Fountain Hills - Fountain Hills Plaza");
		list.put("B53","Fountain Valley - Warner Plaza");
		list.put("B39","Fresno - Fashion Fair Mall");
		list.put("E41","Frisco - N. Summit Blvd.");
		list.put("E7S","Frisco - Parkway Towne Crossing SC GW");
		list.put("EHJ","Gahanna - StoneRidge Plaza");
		list.put("ECD","Geneva - Geneva Commons");
		list.put("E7P","Georgetown - Wolf Ranch GW");
		list.put("A57","Gig Harbor - Borgen");
		list.put("D63","Gilbert - Gilbert Commons");
		list.put("EFO","Gilbert - Gilbert Road");
		list.put("EFX","Gilbert - Santan Village");
		list.put("E99","Glen Allen - Innsbrook Shoppes");
		list.put("D73","Glendale - Colorado Blvd");
		list.put("B64","Glendale - Glendale NW");
		list.put("EDR","Gooding - Main Street");
		list.put("B92","Goodyear - Estrella Marketplace");
		list.put("EFB","Goodyear - Mountain Ranch Marketplace");
		list.put("D62","Goodyear - Palm Valley Marketplace");
		list.put("E9W","Gordonsville - The Shops at Spring Creek");
		list.put("E34","Grand Junction - 7th & North Avenue");
		list.put("E48","Grand Junction - Mesa Mall");
		list.put("E44","Grand Junction - North Avenue");
		list.put("C97","Green Valley - Sahuarita");
		list.put("EHL","Grove City - Turnberry Retail Center");
		list.put("EC9","Gurnee - Gurnee Mills Mall");
		list.put("EDS","Hailey - N. Main Street");
		list.put("E9Z","Hamburg - Tilden Ridge");
		list.put("EDT","Hamilton - N. 1st Street");
		list.put("E8X","Hanover - Arundel Mills");
		list.put("EAR","Harrisburg - High Pointe Commons");
		list.put("EDU","Harrisville - Harrisville Market");
		list.put("D46","Heber City - South Main");
		list.put("EDV","Heber City - Valley Station");
		list.put("EDW","Helena - Helena City Plaza II");
		list.put("E07","Hemet - Page Plaza");
		list.put("E24","Henderson - Lake Mead Crossing");
		list.put("EFA","Henderson - Pebble Marketplace");
		list.put("EGO","Hernando - The Shoppes of Citrus Hill");
		list.put("E7J","Hicksville - High Street");
		list.put("EHN","Highland Heights - The Shoppes at Alpha Place");
		list.put("E45","Highlands Ranch - S. University Blvd.");
		list.put("B14","Hillsboro - Orenco Station");
		list.put("EA9","Hingham - Whiting Street");
		list.put("EFT","Holbrook - Navajo Blvd.");
		list.put("EGP","Holiday - Holiday Centre");
		list.put("EGQ","Homosassa - Shoppes at Sugarmill Woods");
		list.put("C50","Honolulu - Hawaii Kai Towne Center");
		list.put("E9L","Horsham - Horsham Gate");
		list.put("EBZ","Huntington Beach - Adams Avenue");
		list.put("E9P","Huntington Station - Walt Whitman Mall");
		list.put("EFC","Hurricane - Grand Circle Plaza");
		list.put("EAU","Hyde Park - Albany Post Road");
		list.put("EDI","Idaho Falls - E. 17th Street");
		list.put("EES","Idaho Falls - Renaissance Center");
		list.put("EDX","Idaho Falls - Sagewood Center");
		list.put("EAW","Ingram Micro Mobility");
		list.put("EC0","Irvine - Woodbury Town Center");
		list.put("D16","Island City - Island City Shops");
		list.put("EDY","Jerome - Jerome Plaza");
		list.put("EHO","Johnstown - Kyber Run SC");
		list.put("C91","Jordan - The District");
		list.put("EB1","Juneau - Mendenhall Mall");
		list.put("C24","Kailua - Windward T&C");
		list.put("EDZ","Kalispell - Kalispell Center Mall II");
		list.put("EB7","Kennesaw - Barrett Parkway SC");
		list.put("B23","Kennewick - Hwy 395");
		list.put("EE0","Ketchum - Giacobbi Square");
		list.put("D29","Kihei - Piilani Village Shopping Center");
		list.put("EG1","Kingman - Hualapai Mountain Road");
		list.put("E6Q","Kingman - Kingman II SC");
		list.put("EG0","Kingman - Stockton Hill Road");
		list.put("B72","Kirkland - Totem Station");
		list.put("C46","Klamath Falls - Klamath Village");
		list.put("D44","Kona - Kona Commons");
		list.put("EGL","Kuna - Deer Flat Crossing");
		list.put("E74","La Crescenta - Foothill Blvd.");
		list.put("E7C","La Verne - The Commons");
		list.put("B19","Lacey - Marvin Road");
		list.put("A72","Lacey - Pacific Avenue");
		list.put("D32","Lahaina - Lahaina Gateway");
		list.put("E11","Lake Elsinore - City Center");
		list.put("B97","Lake Elsinore - Oak Grove");
		list.put("EG2","Lake Havasu City - Lake Havasu Plaza");
		list.put("EG3","Lake Havasu City - Sunset Plaza");
		list.put("A32","Lake Stevens - Frontier Village");
		list.put("E8C","Lake Wales - Shops on the Ridge");
		list.put("EFU","Lakeside - W. White Mountain Blvd.");
		list.put("EGS","Lakewood Ranch - Lakewood Walk");
		list.put("EGR","Land O Lakes - Collier Commons");
		list.put("E9U","Langhorne - Oxford Valley SC");
		list.put("EGZ","Largo - Bardmoor Promenade");
		list.put("D23","Las Cruces - Main Street");
		list.put("E63","Las Cruces - South Valley");
		list.put("C61","Las Vegas - Blue Diamond Crossing");
		list.put("C40","Las Vegas - Craig Crossing");
		list.put("EFI","Las Vegas - Flamingo Road");
		list.put("E27","Las Vegas - Ft. Apache");
		list.put("E6H","Las Vegas - Highland Plaza");
		list.put("EFF","Las Vegas - Montecito Marketplace");
		list.put("EFV","Las Vegas - Paradise Marketplace");
		list.put("D79","Las Vegas - Trocam Plaza");
		list.put("EBN","Latham - Newton Plaza");
		list.put("D08","Lebanon - South Santiam Highway");
		list.put("E8Z","Lexington - Lexington Crossings");
		list.put("EBR","Liberty - Sullivan Avenue");
		list.put("D42","Liberty Lake - Liberty Lake Road");
		list.put("E6B","Lincoln - Parkway Plaza");
		list.put("E6S","Lincoln City - Lincoln City SC");
		list.put("EGN","Lithia - FishHawk Ranch");
		list.put("EA2","Lititz - Shoppes at Kissel Village");
		list.put("E6Y","Long Beach - Long Beach TC");
		list.put("E68","Long Beach - Marketplace");
		list.put("E47","Longmont - Hover Road");
		list.put("B82","Longview - Washington Way");
		list.put("A22","Los Lunas - Sun Ranch");
		list.put("E9Y","Madison Heights - Madison Heights Plaza");
		list.put("EHP","Maineville - The Shoppes at Grandin");
		list.put("ECJ","Manchester - Mall of New Hampshire");
		list.put("EHQ","Mansfield - Park Avenue West");
		list.put("A60","Maricopa - Maricopa Marketplace");
		list.put("ED3","Marion - Servex Centre");
		list.put("EAL","Marlborough - Marlborough Commons");
		list.put("EAB","Marshfield - The Shops at Ocean's Gate");
		list.put("C77","Marysville - Gateway Center");
		list.put("B99","Marysville - State Avenue");
		list.put("EAC","Mashpee - Mashpee Commons");
		list.put("ED4","Massillon - Lincoln Way");
		list.put("B13","McMinnville - Hwy 99");
		list.put("EBF","Mechanicville - South Central Avenue");
		list.put("EHR","Medina - Montville Centre");
		list.put("EHS","Medina - The Shoppes at River Styx");
		list.put("EET","Meridian - Meridian Marketplace");
		list.put("EE1","Meridian - N. Linder Road");
		list.put("ECK","Merrimack - Merrimack Village Center");
		list.put("EFJ","Mesa - E. McKellips Road");
		list.put("EFH","Mesa - Falcon Gateway");
		list.put("A07","Mesa - McDowell");
		list.put("C89","Mesa - Riverview");
		list.put("D05","Mesa - Talon Airport");
		list.put("EFK","Mesquite - Calais Village II");
		list.put("EFL","Miami - Chaparral Plaza");
		list.put("EHT","Middleburg Heights - Middleburg Towne Square");
		list.put("EBG","Middlebury - Court Street");
		list.put("ED5","Middlefield - Springdale Commons Plaza");
		list.put("EAH","Middletown - West Main");
		list.put("E9D","Midlothian - Tennessee Plaza");
		list.put("E31","Mililani - Town Center of Mililani");
		list.put("B21","Mill Creek - Center Mall");
		list.put("ED6","Minerva - Market Street");
		list.put("EA0","Mohegan Lake - Cortlandt Town Center");
		list.put("EA6","Monmouth Junction - South Brunswick Square");
		list.put("E8R","Monroe - Monroe Mall");
		list.put("A75","Monroe - N. Kelsey");
		list.put("E70","Monrovia - The Gateway");
		list.put("EBK","Monticello - Broadway");
		list.put("E49","Montrose - S. Townsend Avenue");
		list.put("E50","Monument - Jackson Creek Parkway");
		list.put("D98","Morgan Hill - Cochrane Commons SC");
		list.put("C99","Moscow - Palouse Mall");
		list.put("EE2","Mountain Home - Boulevard East");
		list.put("EHU","Mt. Vernon - Mount Vernon View SC");
		list.put("ECP","Mulberry - Church Ave.");
		list.put("EE3","Murray - S. State Street");
		list.put("A89","Murrieta - Murrieta Plaza");
		list.put("E6T","Murrieta - Orchard Stone Creek");
		list.put("EEV","Nampa - 12th Avenue Road");
		list.put("EEQ","Nampa - Garrity Crossing");
		list.put("EEU","Nampa - Treasure Valley Marketplace");
		list.put("E89","Naples - East Tamiami Trail");
		list.put("E88","Naples - N. Tamiami Trail");
		list.put("E8A","Naples - Pebblebrooke Center");
		list.put("EAT","New Bedford - Riverside Landing");
		list.put("ECL","New London - New London SC");
		list.put("EHV","Newark - N. 21st Street");
		list.put("E8V","Newark - Peoples Station");
		list.put("C53","Newberg - Crossroads Plaza");
		list.put("ECM","Newington - Fox Run Mall");
		list.put("EAI","Newport - Newport Town Centre");
		list.put("EA5","Newport News - Jefferson Marketplace");
		list.put("E61","Norco - Gateway TC");
		list.put("E97","Norristown - Valley Forge Marketplace");
		list.put("D50","North Bend - JO Borgen Plaza SC");
		list.put("ECN","North Conway - White Mountain Hwy");
		list.put("EFD","North Las Vegas - Aliante Marketplace");
		list.put("EFE","North Las Vegas - Deer Springs TC");
		list.put("ED7","North Ridgeville - Center Ridge");
		list.put("EBT","North Syracuse - North Main");
		list.put("B44","Oak Harbor - Harbor Station");
		list.put("E8G","Oakland Park - East Commercial");
		list.put("ED8","Oberlin - Oberlin Plaza");
		list.put("EEG","Ogden - S. Harrison Blvd.");
		list.put("EE4","Ogden - The Junction II");
		list.put("EBI","Orange - New Athol Road");
		list.put("ECQ","Orlando - Orange Blossom Trail");
		list.put("EH2","Owosso - Main Street");
		list.put("E7V","Ozark - Hwy 231");
		list.put("E17","Palm Desert - Desert Crossing");
		list.put("E67","Palm Desert - Palm Desert Mall");
		list.put("E12","Palm Desert - Plaza de Hacienda");
		list.put("D97","Palm Springs - Gene Autry Plaza");
		list.put("E75","Palmdale - 10th St.");
		list.put("EBJ","Palmer - Depot Plaza");
		list.put("EG4","Parker - The Shoppes on California Ave");
		list.put("EHW","Parma - Parma Retail");
		list.put("EGU","Parrish - Shops at Silverleaf");
		list.put("E72","Pasadena - Hastings Ranch Plaza");
		list.put("A73","Pasco - Tuscany Plaza SC");
		list.put("EHX","Pataskala - Corylus Drive");
		list.put("EG6","Payson - E. State Hwy 260");
		list.put("EEX","Payson - Growers Grove Blvd.");
		list.put("E7W","Pensacola - Sorrento Plaza");
		list.put("EG7","Peoria - Thunderbird Beltway Plaza");
		list.put("E7Z","Philadelphia - Canal Place");
		list.put("EFM","Phoenix - Cityscape");
		list.put("B17","Phoenix - Ray Rd.");
		list.put("D06","Phoenix - Shops at Cave Creek");
		list.put("EFQ","Phoenix - Tatum Parkplace");
		list.put("D04","Phoenix - Tramonto");
		list.put("EHY","Pickerington - Hunters Run");
		list.put("E8I","Pittsburgh - South Side Town Square");
		list.put("E8W","Plymouth Meeting - The Crossroads");
		list.put("EEY","Pocatello - Rail Crossing SC");
		list.put("EEC","Pocatello - Varsity Square");
		list.put("E9R","Point Pleasant - Point Pleasant SC");
		list.put("EE5","Polson - Main Street");
		list.put("C70","Port Angeles - Bay View");
		list.put("E7I","Port Charlotte - Kings Hwy");
		list.put("EI1","Port Clinton - Harbor Light Landing");
		list.put("B11","Port Hueneme - Mandalay Village");
		list.put("E09","Port Orchard - Sedgwick Road");
		list.put("C82","Porterville - West Henderson");
		list.put("EH5","Portland - Grand River");
		list.put("E6K","Portland - Halsey Square");
		list.put("A27","Portland - Hollywood");
		list.put("C25","Portland - The Shops at Barbur");
		list.put("EDA","Portsmouth - Young Street");
		list.put("B76","Poulsbo - Market Place");
		list.put("E30","Poway - Creekside Plaza");
		list.put("EI0","Powell - The Shoppes at Liberty Crossing");
		list.put("B81","Prescott - Village at the Boulders");
		list.put("EE6","Preston - N. State Street");
		list.put("EEZ","Provo - S. University Avenue");
		list.put("E54","Pueblo - Northern Ave.");
		list.put("E53","Pueblo West - McCulloch Blvd.");
		list.put("C64","Pullman - Crimson Village");
		list.put("C63","Puyallup - Meridian");
		list.put("EG8","Queen Creek - Queen Creek Marketplace");
		list.put("A94","Ramona - Main Street");
		list.put("E7A","Redondo Beach - Hawthorne Blvd.");
		list.put("C17","Reedley - Manning");
		list.put("EE7","Rexburg - Teton River Village");
		list.put("EE8","Rexburg - University Plaza");
		list.put("C85","Richland - Vintner Square");
		list.put("E9I","Richmond - Laburnum Park");
		list.put("A82","Ridgecrest - China Lake Blvd");
		list.put("EE9","Rigby - S. State Street");
		list.put("C75","Rio Rancho - Plaza at Unser");
		list.put("EF1","Riverton - Market Center at Riverton");
		list.put("EGV","Riverview - Summerfield Crossings");
		list.put("E7K","Rocklin - Rocklin Commons");
		list.put("A76","Roseville - Foothills");
		list.put("ECE","Roswell - Connexion at Holcomb Bridge");
		list.put("EA7","Rye Brook - Rye Ridge SC");
		list.put("D54","Sacramento - Arden Town Center");
		list.put("A28","Salem - Market");
		list.put("C98","Salem - Mission Lake Center");
		list.put("A46","Salem - Vista Place");
		list.put("C90","Salt Lake City - Brickyard");
		list.put("E6A","Salt Lake City - Foothill Drive");
		list.put("EAV","Salt Point - Route 44");
		list.put("E7N","San Antonio - Northwoods");
		list.put("C71","San Bernardino - University");
		list.put("D77","San Clemente - Plaza Pacifica");
		list.put("B98","San Diego - 4S Commons");
		list.put("B41","San Diego - College Grove");
		list.put("D59","San Diego - Costa Verde");
		list.put("EBY","San Diego - Fashion Valley Mall II");
		list.put("B94","San Diego - Hillcrest");
		list.put("B50","San Diego - Stonecrest");
		list.put("EC1","San Jacinto - Village at San Jacinto");
		list.put("EC7","San Jose - 55 Holger Way");
		list.put("EC6","San Jose - Blossom Hill Road");
		list.put("EC8","San Jose - North Park Plaza");
		list.put("E28","San Marcos - Grand Plaza SC");
		list.put("EG9 ","San Tan Valley - Pavilions at San Tan Heights");
		list.put("EF0","Sandy - Quarry Bend");
		list.put("E76","Santa Clarita - Golden Valley");
		list.put("E6J","Santa Fe - Devargas");
		list.put("D34","Santa Fe - Market Station");
		list.put("ECR","Sarasota - Sarasota Palms Plaza");
		list.put("EEA","Saratoga Springs - W. Commerce Drive");
		list.put("EGA","Scottsdale - DC Ranch Crossing");
		list.put("A18","Scottsdale - FLW");
		list.put("A10","Scottsdale - Scottsdale Fiesta");
		list.put("E7G","Seattle - California Avenue");
		list.put("D03","Sedona - Sunset Plaza");
		list.put("B84","Sequim - Madison");
		list.put("C45","Shelton - Kneeland");
		list.put("B40","Sherwood - Crossing Center");
		list.put("EA3","Shirley - Southport SC");
		list.put("EDF","Shorewood - Brook Forest Ave.");
		list.put("EGC","Show Low - S. White Mountain Road");
		list.put("E03","Show Low - White Mountain");
		list.put("E96","Sicklerville - Highland Crossing");
		list.put("EC2","Simi Valley - Madera Road");
		list.put("EBH","Slingerlands - Vista Blvd.");
		list.put("E9X","Somerdale - Cooper TC");
		list.put("EAO","Somerset - Crossroads at Somerset");
		list.put("EAP","Southampton - Southampton Shopping Plaza");
		list.put("D35","Spanaway - Mountain Hwy");
		list.put("C33","Spokane - Crosspointe Plaza");
		list.put("A84","Spokane - North Division");
		list.put("B73","Spokane - Shadle Center");
		list.put("A64","Spokane - Sprague");
		list.put("E7H","Spokane Valley - Sprague II");
		list.put("EGX","Spring Hill - Nature Coast Commons");
		list.put("EDB","Springboro - Gardner Road");
		list.put("EGD","Springerville - S. Mountain Avenue");
		list.put("C21","Springfield - Olympic Center");
		list.put("E93","Springfield - Springfield Square");
		list.put("E8H","Squirrel Hill - Forbes Avenue");
		list.put("EGF","St. George - Dixie Sunset Plaza");
		list.put("EFW","St. George - N. Bluff Street");
		list.put("E8J","St. Louis - Southtown");
		list.put("EGY","St. Petersburg - Shoppes at the Royale");
		list.put("D95","Stanwood - Camano Village");
		list.put("E56","Steamboat Springs - Central Park Plaza");
		list.put("E57","Steamboat Springs - S. Lincoln Avenue");
		list.put("EED","Stevensville - Stevi Junction Plaza");
		list.put("E9F","Stowe - Upland Square");
		list.put("EAY","Stuart - Stuart Square");
		list.put("EDH","Surprise - Shops at Prasada");
		list.put("A12","Surprise - Surprise Towne Center");
		list.put("C05","Tacoma - James Center");
		list.put("EH0","Tarpon Springs - Tarpon Mall");
		list.put("E32","Taylor - Silvercreek Plaza");
		list.put("B90","Taylorsville - Taylorsville Center");
		list.put("A86","Temecula - 79 South");
		list.put("D91","Temecula - Temecula TC");
		list.put("E05","Temecula - Winchester Road");
		list.put("EGG","Tempe - Rural Road");
		list.put("EAE","Tewksbury - Wamesit Place");
		list.put("D67","Thousand Oaks - The Oaks");
		list.put("B10","Thousand Oaks - Village at Newbury Park");
		list.put("E8O","Tiffin - Market Street");
		list.put("C31","Tigard - Tigard Marketplace");
		list.put("E8N","Toledo - Ottawa River Road");
		list.put("EGH","Tolleson - Crossroads at Tolleson");
		list.put("D58","Tooele - Tooele Landing SC");
		list.put("D55","Tracy - Crossroads Plaza");
		list.put("EH3","Traverse City - Beitner Road");
		list.put("EDC","Troy - Troy Plaza");
		list.put("C80","Tucson - Broadway Plaza");
		list.put("C81","Tucson - Spanish Trail");
		list.put("EEF","Twin Falls - Blue Lakes Blvd.");
		list.put("E6V","Upland - Colonies Crossroads");
		list.put("EBM","Valatie - US Hwy 9");
		list.put("E77","Valencia - Magic Mountain Parkway");
		list.put("EH1","Valrico - Valrico Commons");
		list.put("B15","Vancouver - Dugan Park");
		list.put("A37","Vancouver - Hazel Dell");
		list.put("EBA","Ventura - Ventura Gateway");
		list.put("EDD","Vermilion - Portland Plaza");
		list.put("EI6","Wadsworth - Wadsworth Crossing");
		list.put("E6N","Walla Walla - Wilbur Avenue");
		list.put("EHM","Warrenville Heights - Harvard Park");
		list.put("EAJ","Warwick - Bald Hill");
		list.put("EFR","Washington - W. Red Cliffs Drive");
		list.put("EI7","Washington Court House - Washington Center");
		list.put("EBU","Watertown - Sams Drive");
		list.put("E8Q","Wauseon - Shoop Avenue");
		list.put("EAQ","Wayne - Gateway Shopping Center");
		list.put("C94","West Bountiful - The Commons");
		list.put("E91","West Chester - Five Points Plaza");
		list.put("E9V","White Plains - The Westchester Mall");
		list.put("E6Z","Whittier - Whittwood Town Center");
		list.put("EFS","Wickenburg - E. Wickenburg Way");
		list.put("EI8","Willoughby Hills - The Plaza at Willoughby Corners");
		list.put("EDE","Wilmington - Wilmington Square II");
		list.put("B79","Wilsonville - Old Town Square");
		list.put("D57","Winchester - French Valley");
		list.put("EGI","Winslow - North Park Plaza");
		list.put("E8E","Winter Haven - Towne Center at Cypress Gardens");
		list.put("EAG","Woburn - Commerce Way");
		list.put("D36","Woodland - Gateway");
		list.put("E58","Woodland Park - Morning Sun Drive");
		list.put("E7Y","Wylie - McCreary Crossing GW");
		list.put("EH4","Wyoming - Village Inn Plaza");
		list.put("D61","Yelm - Creek Street Plaza");
		list.put("EAM","Yonkers - Ridge Hill");
		list.put("B27","Yucaipa - Oak Glen Shopping Center");
		list.put("C95","Yucca Valley - Balsa Ave.");
		list.put("A00","zCorporate Office");
		list.put("A00","zDemo Devices");
		list.put("A95","zWarehouse");

		return list;
	}

}